### ISSUE TITLE
只在样式文件中或以样式语法高亮的文件中显示 CSS Format 菜单，体验会更好

### ISSUE THREAD

**Issue by wangwen1220** [mutian/Sublime-CSS-Format#26]
如果能只在样式文件中或以样式语法高亮的文件中显示 CSS Format 菜单，体验会更好，就像 JSFormat 一样。

**Comment by mutian** [comment]
好建议，等我有时间了处理一下

**Comment by mutian** [comment]
Hi，你的这个需求不能实现，因为Sublime只能隐藏自定义菜单的最后一级。
JSFormat只有一级菜单，所以非JS文件看不到JSFormat的菜单。
而CSS Format有两级菜单，在非样式文件下，已经隐藏了第二级菜单，但是第一级菜单无法隐藏。
这个问题我会记录下来，如果将来有更好的解决方案我会做进一步优化。

**Comment by wangwen1220** [comment]
明白，有待ST接口的进一步优化。
