### ISSUE TITLE
对某些注释的格式化不太友好

### ISSUE THREAD

**Issue by wangwen1220** [mutian/Sublime-CSS-Format#27]
一直在用你的格式化工具，这款工具已经很完美了，感谢作者开发这么好用的工具！
还有一些小地方不是太完美，比如：

#header {
  /*padding: 0;*/
}

格式化后就变成下面这样

#header {
  /* padding: 0;
  */
}

注释被换行了，如果可以设置不格式化注释，或者不让其换行，会更好一些吧

**Comment by mutian** [comment]
目前已经发现了这个问题，处理起来稍微麻烦一些，需要稍微充裕一点的时间处理这个问题

**Comment by wangwen1220** [comment]
辛苦了！支持！

**Comment by mutian** [comment]
已经修复，请更新至最新版本1.0.5
