### ISSUE TITLE
selection is unindented

### ISSUE THREAD

**Issue by hyperknot** [mutian/Sublime-CSS-Format#28]
1. Enable format on save
2. Select some text, for example one selector in LESS
3. If you save with this selection, the selected text will be unindented.
4. If you save with nothing selected, everything will be indented correctly.

**Comment by mutian** [comment]
@hyperknot 

If you select some code, and run format command, only the selection will be formatted. The selection will be regarded as a new context, indentation is only in the new context.

Considering `format_on_save` usage scenario, I disabled selection detect, if you select some code, and save with the selection, the whole file will be formatted and indented.

**Comment by hyperknot** [comment]
Thanks, I agree it make sense on command, it just doesn't make sense on save.
