### ISSUE TITLE
建议：加入保留规则之间空行的选项

### ISSUE THREAD

**Issue by painty** [mutian/Sublime-CSS-Format#35]
有时候我在各个板块之间敲回车来分隔区域，但是cssFormat之后空行都删除了。
例如：

```
div{width:10px;


height:10px;}


span{display:block;}
i{display:block;}
```

格式化之后就成了

```
div{width:10px;height:10px;}
span{display:block;}
i{display:block;}
```

对于css{}括号里面（即css每一条定义之内）的空行，删掉是应该的；对于各条css规则之间的空行，建议可设置选项保留。
期望的结果是：

```
div{width:10px;height:10px;}


span{display:block;}
i{display:block;}
```

**Comment by mutian** [comment]
Hi，我做这个插件的最初目的，是将压缩后的没有任何换行的代码格式化为易读的常见的源码格式，格式化要做得足够彻底，就必须要控制换行格式。

如果你不想清除某些换行，可以试试以下建议：
1. 在需要用换行间隔的代码块前添加注释，声明代码块的用途，插件会自动在规则间的注释前添加换行。
2. 只选中需要格式化的部分，执行格式化命令，插件只会对选中行做操作。
