### ISSUE TITLE
Blank line after each style block

### ISSUE THREAD

**Issue by ylynfatt** [mutian/Sublime-CSS-Format#36]
Would it be possible to have a blank line between each block of CSS? Perhaps it could be incorporated into the `expanded-bs` or have a new setting for this. E.g.

```
body {
    background: #fff;
    font: 12px/2em Arial, Helvetica, sans-serif;
}

a {
    color: rgba(65, 131, 196, 0.8);
}

ol,
ul,
li {
    margin: 0;
    padding: 0;
}
```
Note the blank line after the closing `}`.

**Comment by mutian** [comment]
Thank you for your advise, I have incorporated it to `expanded-bs` command

**Comment by ylynfatt** [comment]
Thanks! :)
