### ISSUE TITLE
建议：给‘break selectors’添加忽略选项

### ISSUE THREAD

**Issue by snadn** [mutian/Sublime-CSS-Format#38]
希望在 break selectors 时可以对没有关系选择符的 selector 进行忽略，或者对有过多的并列选择器的规则进行忽略。

原因：例如对截图中的选择器，若折行，会非常难看且格式化后过长的选择器也不便于阅读。

![image](https://cloud.githubusercontent.com/assets/1269858/8692771/f54451fa-2b03-11e5-9a2a-c13b5e699c0e.png)

**Comment by mutian** [comment]
好建议，我之前也曾考虑过要这么做，但这会给本来操作简洁的插件增加额外的复杂的配置项，增加使用成本。

而且，现在基本都以小模块化形式开发，通过构建流程将多个模块合并出最终的代码，小文件中就不用太在意到格式化成哪种形式了。
