### ISSUE TITLE
Add an option to add an empty newline at the end of document

### ISSUE THREAD

**Issue by jasjuang** [mutian/Sublime-CSS-Format#50]
CSS-Format deletes the empty newline at the end of document which causes conflict with lesshint. Please add an option to disable it.

I believe having a newline at the end of the document is standard, autoformatters and linters such as clang-format and editorconfig all will make newlines at the end of the document

**Comment by mutian** [comment]
First of all, I am very sorry that I have been especially busy in the past two years to deal with this problem until now.
Thank you very much for your patience, and the code you submitted has been merged.
